### ISSUE TITLE
Publish upstream container dockerfile

### ISSUE THREAD

**Issue by Hadlock** [cloggo/tangd#2]
Hi, I am unable to build the container using the dockerfile due to the repo being private (registry.delite.ca/docker/base/node/10:latest). Can you adjust this so that it is buildable from dockerfile source, possibly basing it off of an existing public container. Thank you

**Comment by cloggo** [comment]
For your convenience, I have pushed the base image to the docker hub.  You can build your custom image using the before mentioned based image named cloggo/base:node_10.  There is nothing special about the image, it is derived from node 10 alpine and tini init.
